#!/bin/bash
set -e
openttd-install

SAVE_DIR="${HOME}/.local/share/openttd/save"
AUTOSAVE_DIR="${SAVE_DIR}/autosave"
OPENTTD_ARGS=("-D")

if [[ -n ${SAVE_NAME} ]];then
  # get latest save file by timestamp written
  SAVEFILE=$(find ${AUTOSAVE_DIR} -type f -name "${SAVE_NAME}*" -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
  echo "Found save file ${SAVEFILE}"
fi

if [[ -d "${AUTOSAVE_DIR}" && -n ${DISABLE_LOAD_AUTOSAVE} ]];then
  # get latest autosave file by timestamp written
  SAVEFILE=$(find ${AUTOSAVE_DIR} -type f -name '*.sav' -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" ")
  echo "Found autosave file ${SAVEFILE}"
fi


if [[ -n "${SAVEFILE}" ]];then
  OPENTTD_ARGS+=("-g" "$SAVEFILE")
else
  echo "No savefile found generating new world on startup"
fi

exec $HOME/.games/openttd/openttd "${OPENTTD_ARGS[@]}"
